version: '3.7'
#
# $PWD is mounted as a generic /ISC in the container which then has the 
# /ISC/etc and eventually 
#
services:
  wsdc1:
    build:
      context: ./wsdc
      args:
        COMMIT_ID: ${COMMIT_ID}